"""Added GroupToken + some fixes.

Revision ID: a8f2b3c4f8d1
Revises: 25055ab714b3
Create Date: 2022-06-27 21:48:26.380591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f2b3c4f8d1'
down_revision = '25055ab714b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
