"""Added is_available fiend to Quiz.

Revision ID: f0b03197344f
Revises: b23ec58595fc
Create Date: 2022-06-25 21:39:31.529104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b03197344f'
down_revision = 'b23ec58595fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('is_available', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz', 'is_available')
    # ### end Alembic commands ###
