"""Added Admin table and some user relations.

Revision ID: ebc79c6686db
Revises: f0b03197344f
Create Date: 2022-06-27 16:09:05.215175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc79c6686db'
down_revision = 'f0b03197344f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
