"""Added UUID to attempt.

Revision ID: 27773571fc44
Revises: ea718461c155
Create Date: 2022-07-07 17:00:50.930114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27773571fc44'
down_revision = 'ea718461c155'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempt', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'attempt', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attempt', type_='unique')
    op.drop_column('attempt', 'uuid')
    # ### end Alembic commands ###
