"""Removed QuizToken and moved its functionality to Quiz.

Revision ID: fb1e3dfad45a
Revises: d50ba0ee1e19
Create Date: 2022-07-07 17:40:26.413220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1e3dfad45a'
down_revision = 'd50ba0ee1e19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_token')
    op.add_column('quiz', sa.Column('token', sa.String(length=10), nullable=False, server_default='basedbased'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz', 'token')
    op.create_table('quiz_token',
    sa.Column('token', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], name='quiz_token_quiz_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name='quiz_token_pkey'),
    sa.UniqueConstraint('quiz_id', name='quiz_token_quiz_id_key')
    )
    # ### end Alembic commands ###
