"""Added GroupToken + some fixes 2.

Revision ID: 75c746ca99fd
Revises: a8f2b3c4f8d1
Create Date: 2022-06-27 21:49:11.565666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c746ca99fd'
down_revision = 'a8f2b3c4f8d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_token',
    sa.Column('token', sa.String(length=10), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token'),
    sa.UniqueConstraint('group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_token')
    # ### end Alembic commands ###
