"""Changed group desctiption length power-2-wise (to 512)

Revision ID: 390db3fea026
Revises: 75c746ca99fd
Create Date: 2022-06-27 22:04:31.201203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390db3fea026'
down_revision = '75c746ca99fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
