"""Fixed attempt

Revision ID: d50ba0ee1e19
Revises: 27773571fc44
Create Date: 2022-07-07 17:13:25.403885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50ba0ee1e19'
down_revision = '27773571fc44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attempt_answer', 'mark',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attempt_answer', 'mark',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###
