"""Changed mark server default to 0.

Revision ID: f0c0cfbd8a57
Revises: 040ad8dca621
Create Date: 2022-07-07 14:49:46.352224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c0cfbd8a57'
down_revision = '040ad8dca621'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
