"""Removed id from Admin

Revision ID: a0706532f208
Revises: 5ce3c05a64b4
Create Date: 2022-07-11 21:37:27.107439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0706532f208'
down_revision = '5ce3c05a64b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_user_id_key', 'admin', type_='unique')
    op.drop_constraint('admin_user_id_fkey', 'admin', type_='foreignkey')
    op.drop_column('admin', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.create_foreign_key('admin_user_id_fkey', 'admin', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('admin_user_id_key', 'admin', ['user_id'])
    # ### end Alembic commands ###
