"""Added Admin table try 4.

Revision ID: 0b2d96a97ee8
Revises: 2675b518f5f3
Create Date: 2022-06-27 16:22:28.247945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2d96a97ee8'
down_revision = '2675b518f5f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_unique_constraint(None, 'admin', ['user_id'])
    op.drop_constraint('admin_user_id_fkey', 'admin', type_='foreignkey')
    op.create_foreign_key(None, 'admin', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.create_foreign_key('admin_user_id_fkey', 'admin', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'admin', type_='unique')
    op.alter_column('admin', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
