"""Fixed GroupMember - Group relationship.

Revision ID: 25055ab714b3
Revises: 0b2d96a97ee8
Create Date: 2022-06-27 21:24:39.338371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25055ab714b3'
down_revision = '0b2d96a97ee8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('is_public', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'group', 'user', ['is_public'], ['id'], ondelete='CASCADE')
    op.drop_constraint('group_member_group_id_fkey', 'group_member', type_='foreignkey')
    op.create_foreign_key(None, 'group_member', 'group', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_member', type_='foreignkey')
    op.create_foreign_key('group_member_group_id_fkey', 'group_member', 'user', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'is_public')
    # ### end Alembic commands ###
